### PR TITLE
Explicitly raise an error if `MAXMIND_LICENSE_KEY` is not set

### LINKED ISSUE #4: Make missing maxmind license key env variable error more clear
Currently, when trying to compile `geoid-elixir` with an unset Maxmind license key, it will simply fail with an obscure error message.

I think the library should explicitly check that the env var is set during compilation, and raise a clear error if it is missing.

### PR DESCRIPTION
**Pull request by danirukun**
Closes #4

### CODE REVIEW

File: config/config.exs [hunk 1]
```diff
@@ -1,6 +1,13 @@
 import Config
 
 config :geo,
-  maxmind_license_key: System.get_env("MAXMIND_LICENSE_KEY")
+  maxmind_license_key:
+    System.get_env("MAXMIND_LICENSE_KEY") ||
```
Comment (abangratz) [inline config/config.exs:5]: I guess [`System.fetch_env!/1`](https://hexdocs.pm/elixir/1.13/System.html#fetch_env!/1) could also have worked, but would be less explicit.

**Review by abangratz — APPROVED** [review]

**Review by yanko-platogo — APPROVED** [review]

File: config/config.exs (hunk 1 above)
Comment (danirukun) [reply config/config.exs:5]: Yup, exactly the reason 😄
